### ISSUE TITLE
Scène Menu principal

### ISSUE THREAD

**Issue by TKiraa** [TKiraa/Battle-JEARCE#2]
Créer une nouvelle scène qui sera dédié à l'accueil, 
Elle sera constitué d'un canvas avec 4 boutons (non définitif) de : 

- Jouer (si connecté) / Connexion (si pas connecté)
- Inscription (optionnel)
- Option
- Quitter

**Comment by Ronan93** [comment]
La scène accueil est fini pour le moment (il manque les liens vers le site internet une fois réaliser et des vérifications lié à la base de données)
J'ai aussi fait la scène Menu Principal avec les boutons options et quitter mais aussi un bouton classement, formation, jeu amical et jouer

**Comment by Ronan93** [comment]
les options et le soundmanager reste bien identique entre les scènes
