### ISSUE TITLE
Classes pour chaque Personnage

### ISSUE THREAD

**Issue by ClementineRoth** [TKiraa/Battle-JEARCE#4]
développer les classe définissent les différent rôle des personnages avec les stats :

-vie
-attaque
-deplacement

**Comment by kira370** [comment]
La Classe personnage existe, il faut que tu fasses des prefabs pour chaque units.

la classe : https://github.com/kira370/Battle-JEARCE/blob/master/Unity/ProjetUnity/Assets/Scripts/Character.cs
